name: Code Security

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Weekly security check

jobs:
  security:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .js --max-warnings=0

      - name: Check formatting
        run: npx prettier --check .

      - name: Security audit
        run: |
          npm audit --production --audit-level=high
          if [ $? -ne 0 ]; then
            echo "Critical vulnerabilities found!"
            exit 1
          fi